Import('env')
src_exe = [
    'test_static.c',
    'test_mini.c',
    'test_unweighted.c',
    'test_weighted.c',
    'test_components.c',
    'test_repeat.c',
]
src_lib = [
    'dybc_test_common.c',
    'minigraph.c',
]
#print([str(s) for s in Glob('test_*.c')])
prog = [env.Program([s]+src_lib) for s in src_exe]
Return('prog')
