---
title: "研究進捗報告"
author: "里谷 佳紀"
date: "2019年10月4日"
documentclass: bxjsarticle
classoption: xelatex,ja=standard,11pt
geometry: false
header-includes:
  - \usepackage{xltxtra}
  - \usepackage{zxjatype}
  - \usepackage[ipaex]{zxjafont}
output:
  pdf_document:
    latex_engine: xelatex
    template: mytemplate.tex
    number_sections: true
    fig_caption: true
  github_document:
    html_preview: false
---

```{r setup, include = FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
theme_set(theme_light(base_size = 11, base_family = 'IPAexGothic'))
if(knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex') {
  devname <- 'cairo_pdf'
  devargs <- c(family = 'IPAexGothic')
} else {
  devname <- 'png'
  devargs <- c(family = 'IPAexGothic', type = 'cairo-png')
}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.height = 8, fig.width = 6, fig.align = 'center',
  dev = devname, dev.args = devargs, dpi = 150
)
```

```{r readin, include = FALSE}
data_time <- read_csv('../res/data/misc.csv') %>%
  select(c('order', 'size', 'gml', 'time-proposed', 'time-brandes')) %>%
  rename(network = gml) %>%
  mutate(network = sub('.gml', '', basename(network))) %>%
  gather(
    key = 'method', value = 'time',
    `time-proposed`, `time-brandes`
  ) %>%
  mutate(method = sub('time-', '', method)) %>%
  group_by(network, order, size, method) %>%
  summarise(mean = mean(time), max = max(time)) %>%
  gather(Var, val, `mean`, `max`) %>%
  unite(Var1, method, Var, sep = '-') %>%
  spread(Var1, val) %>%
  ungroup()
```

# 研究全体の目的
グラフと全頂点間距離と最短経路の数および依存度が与えられたとき，グラフの辺が削除されたとする．
このときの全頂点間距離と最短経路の数と依存度を高速に更新する方法を開発する．
また，実験と理論の両方から既存の方法と比較することで，新方法の有用性を検証する．

# 前回打ち合わせ時に定めた短期目標
1. 実ネットワーク上の実験の実施と結果のまとめ．前回渡した論文の下書きでは，email-Enronデータセットに対して2回しか実行できていなかったので，10回実験を行った．

# 本日までの進捗状況
1. 実験が完了した．結果を以下に示す．

```{r tab1}
knitr::kable(data_time, digits = 3)
```

