---
title: "研究進捗報告"
author: "里谷 佳紀"
date: "平成30年5月22日"
documentclass: bxjsarticle
classoption: xelatex,ja=standard,11pt
geometry: false
header-includes:
  - \usepackage{xltxtra}
  - \usepackage{zxjatype}
  - \usepackage[ipaex]{zxjafont}
output:
  pdf_document:
    latex_engine: xelatex
    template: mytemplate.tex
    number_sections: true
    fig_caption: true
  github_document:
    html_preview: false
---

```{r setup, include = FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
library(gridExtra)
theme_set(theme_light(base_size = 11, base_family = 'IPAexGothic'))
knitr::opts_knit$get('rmarkdown.pandoc.to')
if(knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex') {
  devname <- 'cairo_pdf'
  devargs <- c(family = 'IPAexGothic')
} else {
  devname <- 'png'
  devargs <- c(family = 'IPAexGothic', type = 'cairo-png')
}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.height = 2.3, fig.width = 6, fig.align = 'center',
  dev = devname, dev.args = devargs, dpi = 150
)
```

# 研究全体の目的
グラフと全頂点間距離と最短経路の数およびペア依存度が与えられたとき，グラフの辺が削除されたとする．
このときの全頂点間距離と最短経路の数とペア依存度を高速に更新する方法を開発する．
また，実験と理論の両方から既存の方法と比較することで，新方法の有用性を検証する．

# 前回打ち合わせ時に定めた短期目標
1. 電子情報通信学会の発表スライドの作成
2. アルゴリズムごとのデータの整理

# 本日までの進捗状況
1. 着手している．発表の流れを決め，いくつかのスライドを作成した．
2. 次節で説明する．

# 各アルゴリズムの比較
昨年度，初期グラフと枝刈りの有無を変えて実験した．その結果を示す．

```{r read, echo = TRUE, message = FALSE}
data_url = paste0('https://raw.githubusercontent.com/y-satotani/gmg-finder/',
                  'master/docs/res/data/the-cmp-algo-lab.csv')
data <- read_csv(data_url) %>%
  filter(sorted == 'basic', sinitr %in% c('basic', 'minmax')) %>%
  group_by(n, d, ginitr, sinitr) %>%
  summarise(n_state = mean(n_state), time = mean(time))
```

```{r fig1, echo = TRUE, fig.width = 4, fig.height = 5, fig.caption = '次数3'}
# 次数3
qs <- ggplot(data %>% filter(d == 3),
  aes(n, n_state, colour = ginitr, linetype = sinitr, shape = sinitr)) +
  geom_line() + geom_point() +
  labs(x = '頂点数', y = '展開状態数') +
  scale_y_log10()
qt <- ggplot(data %>% filter(d == 3),
aes(n, time, colour = ginitr, linetype = sinitr, shape = sinitr)) +
  geom_line() + geom_point() +
  labs(x = '頂点数', y = '実行時間[s]') +
  scale_y_log10()
grid.arrange(qs, qt, ncol = 1)
```

```{r fig2, echo = TRUE, fig.width = 4, fig.height = 5, fig.caption = '次数4'}
# 次数4
qs <- ggplot(data %>% filter(d == 4),
  aes(n, n_state, colour = ginitr, linetype = sinitr, shape = sinitr)) +
  geom_line() + geom_point() +
  labs(x = '頂点数', y = '展開状態数') +
  scale_y_log10()
qt <- ggplot(data %>% filter(d == 4),
aes(n, time, colour = ginitr, linetype = sinitr, shape = sinitr)) +
  geom_line() + geom_point() +
  labs(x = '頂点数', y = '実行時間[s]') +
  scale_y_log10()
grid.arrange(qs, qt, ncol = 1)
```
