
#include <stdio.h>
#include <string.h>
#include <argp.h>
#include <igraph/igraph.h>
#include "dybc_exp_common.h"

const char *argp_program_version =
  "exp-compare-performance beta";
const char *argp_program_bug_address =
  "https://github.com/y-satotani/dynamic-betweenness/issues";
struct arguments {
  char* input_file;
  char* cache_file;
  char* output_file;
  int is_directed;
};
static struct argp_option options[] = {
  {"directed", 'd', 0, 0, "compute for directed graph"},
  {"cache", 'c', "CACHE_FILE", 0, "cache file generated by cache computer"},
  {0}
};
static error_t parse_opt(int key, char *arg, struct argp_state *state) {
  struct arguments *arguments = state->input;
  switch (key) {
  case 'd':
    arguments->is_directed = 1;
    break;
  case 'c':
    arguments->cache_file = arg;
    break;
  case ARGP_KEY_ARG:
    if(state->arg_num == 0)
      arguments->input_file = arg;
    else if(state->arg_num == 1)
      arguments->output_file = arg;
    else
      argp_usage(state);
    break;
  case ARGP_KEY_END:
    if(state->arg_num < 2)
      argp_usage(state);
    break;
  default:
    return ARGP_ERR_UNKNOWN;
  }
  return 0;
}
static char args_doc[] = "IN OUT";
static char doc[] = "";
static struct argp argp = {options, parse_opt, args_doc, doc};

int main(int argc, char* argv[]) {
  struct arguments arguments;
  arguments.input_file = NULL;
  arguments.output_file = NULL;
  arguments.is_directed = 0;
  arguments.cache_file = NULL;
  argp_parse (&argp, argc, argv, 0, 0, &arguments);

  FILE* istream;
  if(strcmp(arguments.input_file, "-") == 0) istream = stdin;
  else istream = fopen(arguments.input_file, "r");

  igraph_t G;
  igraph_vector_t weights;
  dybc_read_edgelist(&G, &weights, arguments.is_directed, istream);
  fclose(istream);

  igraph_matrix_t D;
  igraph_matrix_int_t S;
  igraph_vector_t B;
  igraph_matrix_init(&D, 0, 0);
  igraph_matrix_int_init(&S, 0, 0);
  igraph_vector_init(&B, 0);
  if(arguments.cache_file) {
    FILE* cistream;
    if(strcmp(arguments.cache_file, "-") == 0) cistream = stdin;
    else cistream = fopen(arguments.cache_file, "r");
    dybc_load_cache(&D, &S, &B, cistream);
    fclose(cistream);
  } else {
    igraph_vector_t* W;
    if(igraph_ecount(&G) == igraph_vector_size(&weights)) {
      W = &weights;
    } else {
      if(igraph_vector_size(&weights) > 0)
        printf("Warning: length of weights is different from size. Discarding weights\n");
      W = 0;
    }
    betweenness_with_redundant_information(&G, &D, &S, &B, W);
  }

  FILE* ostream;
  if(strcmp(arguments.output_file, "-") == 0) ostream = stdout;
  else ostream = fopen(arguments.output_file, "wb");
  fclose(ostream);

  igraph_matrix_destroy(&D);
  igraph_matrix_int_destroy(&S);
  igraph_vector_destroy(&B);
  igraph_destroy(&G);
  igraph_vector_destroy(&weights);
  return 0;
}
